[package]
name = "app"
version = "0.1.0"
edition.workspace = true

[dependencies]
bot-core = { workspace = true }
channel-telegram-bot = { workspace = true }
contracts = { workspace = true }
llm-timeweb = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
storage-fs = { workspace = true }
teloxide = "0.17.0"
tokio = { workspace = true }
tracing = { workspace = true }

clap = { version = "4", features = ["derive"] }
config = { version = "0.15.25", default-features = false, features = ["toml"] }
dotenvy = "0.15.7"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
